name: CI - Build and Test

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files in demo directory
        run: ls -la
        working-directory: ./demo

      - name: Build Java
        run: mvn clean install -DskipTests
        working-directory: ./demo

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        run: mvn test
        working-directory: ./demo
